# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- dev

pool:
  totostore-ci

variables:
  buildConfiguration: 'Release'
  workDir: '/home/hoaith/projects/Totostore.Backend/'

steps:
- script:
  workingDirectory: $(workDir)  
   |
    git pull
    ls
  displayName: 'Run update stack commands'
